BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "reding_content" (
	"3rdgrade"	TEXT,
	"4thgrade"	TEXT,
	"5thgrade"	TEXT,
	"6thgrade"	TEXT,
	"7thgrade"	TEXT
);
INSERT INTO "reding_content" VALUES ('https://youtu.be/as7xe8UQEr4 - summarizing nonfiction','https://youtu.be/as7xe8UQEr4 - summarizing nonfiction','https://youtu.be/jeDCQhJqD7o - Making objective summaries of literary texts','https://youtu.be/gUW2jit3uvo - Making inferences in informational texts','https://youtu.be/gUW2jit3uvo - Making inferences in informational texts');
INSERT INTO "reding_content" VALUES ('https://youtu.be/4swFGRhQoMI - What is a main idea?','https://youtu.be/4swFGRhQoMI - What is a main idea?','https://youtu.be/tW9TG22U3Go - Character actions in stories','https://youtu.be/5Eepm6Px5pc - Creating objective summaries','https://youtu.be/GvWH9ZXy9gY - How can a text have two or more main ideas?');
INSERT INTO "reding_content" VALUES ('https://youtu.be/Ox_JaA6nX_Q - Finding connections between ideas within a passage','https://youtu.be/TiORG0pHskE - What language shows cause and effect','https://youtu.be/XIfYK4tpl2Y - How POV affects readers','https://youtu.be/GvWH9ZXy9gY - How can a text have two or more main ideas?','https://youtu.be/l3yWmXbC36s - Analyzing tone through word choice');
INSERT INTO "reding_content" VALUES ('https://youtu.be/v6EDEr_20sc - Using text features to locate information','https://youtu.be/D0YUpfLofgQ - The structures of informational texts','https://youtu.be/0zoZmYbJ3tE - What do pictures bring to a story?','https://youtu.be/g9qWsEJakbQ - How do writers use examples to get their points across?','https://youtu.be/Tq_BoPJsv-4 - Citing evidence in literary analysis');
INSERT INTO "reding_content" VALUES ('https://youtu.be/gUW2jit3uvo - Making inferences in informational texts','https://youtu.be/iP7HnX5mr5c - Looking back at the text for evidence','https://youtu.be/gUW2jit3uvo - Making inferences in informational texts','https://youtu.be/D0YUpfLofgQ - The structures of informational texts','https://youtu.be/msHjgIsYOkU - Incorporating opposing viewpoints');
INSERT INTO "reding_content" VALUES ('https://youtu.be/v4HhzvSgUpU - Evaluating a source’s reasoning and evidence','https://youtu.be/v7QuOr1PP7o - Characters’ thoughts and feelings','https://youtu.be/4swFGRhQoMI - What is a main idea?','https://youtu.be/R_bgo8j6jxc - Analyzing an author’s purpose','https://youtu.be/Q4I9ht7wHsk - How the delivery of a speech affects the impact of the words');
INSERT INTO "reding_content" VALUES ('https://youtu.be/lcXgSEF4iCM - Reading more than one source on topic','https://youtu.be/lzKj-bLvrYQ - Figurative language','https://youtu.be/g9qWsEJakbQ - How do writers use examples to get their points across?','https://youtu.be/NXO3KT8bne4 - What is an argument?','https://youtu.be/CiNggzdWkIo - Using context clues to figure out new words');
INSERT INTO "reding_content" VALUES ('https://youtu.be/CiNggzdWkIo - Using context clues to figure out new words','https://youtu.be/GGS3NcmAZnw - A story’s point of view','https://youtu.be/R_bgo8j6jxc - Analyzing an author’s purpose','https://youtu.be/WzQGeCzOTyk - Quantitative information in texts','https://youtu.be/lzKj-bLvrYQ - Figurative language');
INSERT INTO "reding_content" VALUES ('https://youtu.be/lzKj-bLvrYQ - Figurative language','https://youtu.be/0zoZmYbJ3tE - What do pictures bring to a story?','https://youtu.be/tQhLQQcJZyo - Reading multiple accounts of the same topic','https://youtu.be/CiNggzdWkIo - Using context clues to figure out new words','https://youtu.be/XRt1N0sJJQo - Connotation');
INSERT INTO "reding_content" VALUES ('https://youtu.be/v7QuOr1PP7o - Characters’ thoughts and feelings','https://youtu.be/CiNggzdWkIo - Using context clues to figure out new words','https://youtu.be/INFWXZ_tl4M - Making inferences in literary texts','https://youtu.be/lzKj-bLvrYQ - Figurative language','https://youtu.be/5Eepm6Px5pc - Creating objective summaries');
INSERT INTO "reding_content" VALUES ('https://youtu.be/tW9TG22U3Go - Character actions in stories','https://youtu.be/fiaPqgwJFo4 - Latin and Greek roots and affixes','https://youtu.be/CiNggzdWkIo - Using context clues to figure out new words','https://youtu.be/l3yWmXbC36s - Analyzing tone through word choice','https://youtu.be/-GY2Cj1w_PY - Part-to-whole relationships in text structure');
INSERT INTO "reding_content" VALUES ('https://youtu.be/0zoZmYbJ3tE - What do pictures bring to a story?','https://youtu.be/MAu3e5GZo4k - Understanding theme','https://youtu.be/lzKj-bLvrYQ - Figurative language','https://youtu.be/XRt1N0sJJQo - Connotation','https://youtu.be/NXO3KT8bne4 - What is an argument?');
INSERT INTO "reding_content" VALUES ('https://youtu.be/LO21tYrTD8Y - The elements of a poem','https://youtu.be/tW9TG22U3Go - Character actions in stories','https://youtu.be/D2FFijvA00I - Developing themes','https://youtu.be/INFWXZ_tl4M - Making inferences in literary texts','https://youtu.be/fiaPqgwJFo4 - Latin and Greek roots and affixes');
INSERT INTO "reding_content" VALUES ('https://youtu.be/GGS3NcmAZnw - A story’s point of view','https://youtu.be/Zr1xLtSMMLo - The elements of a story','https://youtu.be/KC6WY06twwc - Character change','https://youtu.be/KC6WY06twwc - Character change','https://youtu.be/Zr1xLtSMMLo - The elements of a story');
INSERT INTO "reding_content" VALUES ('https://youtu.be/NbTeg3Fe_Ys - Relationships between scientific ideas in a text','https://youtu.be/imlwmNO9xlY - The elements of a drama','https://youtu.be/YxXfltZZOdI - Reading within and across genres','https://youtu.be/Zr1xLtSMMLo - The elements of a story','https://youtu.be/ZASEsKwEvqE - Different mediums and the tone of the text');
INSERT INTO "reding_content" VALUES ('https://youtu.be/Zx2A9WAswCo - Interpreting text features','https://youtu.be/1clS_RN6NuI - Reading (and comparing) multiple books','https://youtu.be/GvWH9ZXy9gY - How can a text have two or more main ideas?','https://youtu.be/imlwmNO9xlY - The elements of a drama','https://youtu.be/INFWXZ_tl4M - Making inferences in literary texts');
INSERT INTO "reding_content" VALUES ('https://youtu.be/iP7HnX5mr5c - Looking back at the text for evidence','https://youtu.be/Zx2A9WAswCo - Interpreting text features','https://youtu.be/WzQGeCzOTyk - Quantitative information in texts','https://youtu.be/XIfYK4tpl2Y - How POV affects readers','https://youtu.be/R_bgo8j6jxc - Analyzing an author’s purpose');
INSERT INTO "reding_content" VALUES ('https://youtu.be/Tevlz2S2Mzk - Messages and morals','https://youtu.be/v4HhzvSgUpU - Evaluating a source’s reasoning and evidence','https://youtu.be/lcXgSEF4iCM - Reading more than one source on topic','https://youtu.be/ZASEsKwEvqE - Different mediums and the tone of the text','https://youtu.be/lcXgSEF4iCM - Reading more than one source on topic');
INSERT INTO "reding_content" VALUES ('https://youtu.be/SmnR4AZ-XM8 - Summarizing stories','https://youtu.be/rf8FX2sI3gU - How to grow my brain','https://youtu.be/fiaPqgwJFo4 - Latin and Greek roots and affixes','https://youtu.be/-GY2Cj1w_PY - Part-to-whole relationships in text structure','https://youtu.be/D2FFijvA00I - Developing themes');
INSERT INTO "reding_content" VALUES ('https://youtu.be/WYSnf6qy4WA - What are affixes','https://youtu.be/INFWXZ_tl4M - Making inferences in literary texts','https://youtu.be/XRt1N0sJJQo - Connotation','https://youtu.be/D2FFijvA00I - Developing themes','https://youtu.be/LO21tYrTD8Y - The elements of a poem');
INSERT INTO "reding_content" VALUES ('https://youtu.be/TiORG0pHskE - What language shows cause and effect','https://youtu.be/SmnR4AZ-XM8 - Summarizing stories','https://youtu.be/5Eepm6Px5pc - Creating objective summaries','https://youtu.be/LO21tYrTD8Y - The elements of a poem','https://youtu.be/XIfYK4tpl2Y - How POV affects readers');
INSERT INTO "reding_content" VALUES ('https://youtu.be/INFWXZ_tl4M - Making inferences in literary texts','https://youtu.be/gUW2jit3uvo - Making inferences in informational texts','https://youtu.be/NXO3KT8bne4 - What is an argument?','https://youtu.be/YxXfltZZOdI - Reading within and across genres',NULL);
INSERT INTO "reding_content" VALUES ('https://youtu.be/MAu3e5GZo4k - Understanding theme','https://youtu.be/MAu3e5GZo4k - Understanding theme','https://youtu.be/v4HhzvSgUpU - Evaluating a source’s reasoning and evidence','https://youtu.be/fiaPqgwJFo4 - Latin and Greek roots and affixes',NULL);
INSERT INTO "reding_content" VALUES ('https://youtu.be/Zr1xLtSMMLo - The elements of a story','https://youtu.be/LO21tYrTD8Y - The elements of a poem','https://youtu.be/LO21tYrTD8Y - The elements of a poem','https://youtu.be/lcXgSEF4iCM - Reading more than one source on topic',NULL);
INSERT INTO "reding_content" VALUES ('https://youtu.be/1clS_RN6NuI - Reading (and comparing) multiple books','https://youtu.be/vb0xGhKoFQ0 - First and secondhand accounts','https://youtu.be/ZASEsKwEvqE - Different mediums and the tone of the text',NULL,NULL);
INSERT INTO "reding_content" VALUES (NULL,'https://youtu.be/lcXgSEF4iCM - Reading more than one source on topic','https://youtu.be/Zx2A9WAswCo - Interpreting text features',NULL,NULL);
INSERT INTO "reding_content" VALUES (NULL,NULL,'https://youtu.be/D0YUpfLofgQ - The structures of informational texts',NULL,NULL);
INSERT INTO "reding_content" VALUES (NULL,NULL,'https://youtu.be/Zr1xLtSMMLo - The elements of a story',NULL,NULL);
COMMIT;
